/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-modules-e3ba39a1c78540448542cf937b11feab
Title: Space Station Modules
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/space_station_modules/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.175}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship001_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship002_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship003_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship004_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship005_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship006_low_spaceship_0.geometry}
            material={materials.spaceship}
            position={[0, 0, 1081.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship001_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship002_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship003_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship004_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship005_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.spaceship006_low001_spaceship_0.geometry}
            material={materials.spaceship}
            position={[214.53, 4472.068, -1679.137]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/space_station_modules/scene.gltf')
